name: Justfile Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-justfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Flox
        run: |
          curl -sS https://get.flox.dev/install | bash
          echo "$HOME/.flox/bin" >> $GITHUB_PATH

      - name: Setup Flox Environment
        run: |
          flox init
          flox install just pnpm node wasm-pack postgresql netcat
          echo "FLOX_ENV=local/catcolab-test" >> $GITHUB_ENV

      - name: Setup CatColab with Flox
        run: |
          just setup

      - name: Setup Database
        run: |
          just db-setup
          # Verify database connection and environment
          grep -q "DATABASE_URL=postgres://localhost:6969/catcolab" .env
          test -f .postgres-data/postgresql.conf

      - name: Build Frontend
        run: |
          cd packages/frontend && pnpm run build
